FROM python:3.11

RUN apt update
RUN apt install -y gcc

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install transformers sentencepiece gradio accelerate bitsandbytes pyyaml

