apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
  - pvc.yaml
  - deployment-galactica.yaml

patches:
  - path: patch.yaml
