---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: chatbot
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: nfs
  