---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: override
        ports:
        - containerPort: 7860
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: chatbot
spec:
  type: ClusterIP
  ports:
  - port: 7860
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: chatbot
